language: python
python:
    - "2.7"

branches:
    only:
        - master

virtualenv:
    system_site_packages: true

before_script:
    - echo "deb http://ppa.launchpad.net/lmr/autotest/ubuntu utopic main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -q
    - sudo apt-get -y --force-yes install autotest

install:
    - pip install sphinx tox simplejson MySQL-python pylint autopep8
    - pip install inspektor
    - pip install -r requirements.txt

script:
    - ./tools/run_unittests_nose.py -c .nose.cfg -s virttest
    - inspekt lint
    - inspekt style
    - ./tools/build_docs.py

notifications:
  irc:
    channels: "irc.oftc.net#virt-test"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
